#
# Sunbeam configuration file
#
# Defining samples:
#   Run 'sunbeam list_samples <data_dir>' to create a list of samples and
#   associated fastq.gz files. Samples must be in gzipped fastq format.
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options
all:
  root: /projects/of33/Celine/MetaGenomics
  output_fp: sunbeam_output
  samplelist_fp: samples.csv
  paired_end: true
  download_reads: false
  version: 2.1.0

# Quality control
qc:
  suffix: qc
  # Trimmomatic
  threads: 16
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4, 15]
  minlen: 36
  adapter_fp: /home/cpat0003/miniconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa
  # Cutadapt
  fwd_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  rev_adapters: [GTTTCCCAGTCACGATC, GTTTCCCAGTCACGATCNNNNNNNNNGTTTCCCAGTCACGATC]
  # Komplexity
  kz_threshold: 0.55
  # Decontam.py
  pct_id: 0.5
  frac: 0.6
  host_fp: /home/cpat0003/of33/Databases/shotgun/host/human/sunbeam/metagenome

# Taxonomic classifications
classify:
  suffix: classify
  threads: 16
  kraken_db_fp: ''

# Contig assembly
assembly:
  suffix: assembly
  min_length: 400
  threads: 16

# Annotation
annotation:
  suffix: annotation
  min_contig_len: 400
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500

blast:
  threads: 16

blastdbs:
  root_fp: /home/cpat0003/of33/Databases/shotgun/blast
  nucleotide:
    nt: nt_20211102
  protein:
    nr: nr_20211102

mapping:
  suffix: mapping
  genomes_fp: ''
  samtools_opts: ''
  threads: 16

download:
  suffix: download
  threads: 16

sbx_kraken2bracken:
  threads: 16
  db: /home/cpat0003/of33/Databases/shotgun/kraken/kraken20210613
  read_length: 250

sbx_coassembly:
  threads: 16
  group_file: ''

sbx_anvio:
  threads: 16
  min_len: 1000
  pfam_dir: /home/cpat0003/of33/Databases/shotgun/anvio
  kaiju_dir: /home/cpat0003/of33/Databases/shotgun/kaiju

sbx_deepARG:
  deepARG_dir: /home/cpat0003/of33/Databases/shotgun/deepARG
